services:
    wegeland.speciallang.controller.acp:
        class: wegeland\speciallang\controller\acp_controller
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@config'
            
    wegeland.speciallang.listener:
        class: wegeland\speciallang\event\listener
        arguments:
         - '@config'
         - '@template'
        tags:
            - { name: event.listener }
